name: Deploy ADF with Linked Templates (UAMI-based)

on:
  push:
    branches: [main]

jobs:
  deploy-adf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Azure Login using UAMI
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install ADF Template Generator
      run: |
        git clone https://github.com/Azure/Azure-DataFactory-Utilities.git
        cd Azure-DataFactory-Utilities/ARMTemplateGenerator
        npm install

    - name: Export ADF Templates
      run: |
        cd Azure-DataFactory-Utilities/ARMTemplateGenerator
        npm run build export \
          "${{ github.workspace }}/MyADF" \
          "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_NAME }}" \
          adf-arm-output

    - name: Upload Linked Templates to Storage Account
      run: |
        az storage blob upload-batch \
          --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
          --destination ${{ secrets.CONTAINER_NAME }}/LinkedTemplates \
          --source ./Azure-DataFactory-Utilities/ARMTemplateGenerator/adf-arm-output/LinkedTemplates \
          --auth-mode login

    - name: Patch Main Template with Linked Template URIs (No SAS)
      run: |
        storageUrl="https://${{ secrets.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/${{ secrets.CONTAINER_NAME }}/LinkedTemplates"
        sas="${{ secrets.ST_SAS_TOKEN }}"
        jq --arg url "$url" --arg sas "$sas" '
        .resources |= map(
          if .type == "Microsoft.Resources/deployments" and .properties.templateLink != null then
            .properties.templateLink.uri = ($url + "/" + (.name) + ".json" + "?" + $sas)
            | del(.properties.templateLink.contentVersion)
          else
            .
          end
        )
        | del(.parameters.containerUri)
        | del(.parameters.containerSasToken)
        ' ARMTemplateForFactory.json > PatchedTemplate.json

    - name: Deploy Patched Template to Azure
      run: |
        az deployment group create \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --template-file ./main-template-patched.json \
          --parameters "@./Azure-DataFactory-Utilities/ARMTemplateGenerator/adf-arm-output/ARMTemplateParametersForFactory.json"
