name: ADF Deployment with Linked Templates via UAMI

on:
  push:
    branches: [ main ]

env:
  STORAGE_ACCOUNT_NAME: 'yourstorageaccount'
  CONTAINER_NAME: 'arm-templates'
  RESOURCE_GROUP: 'your-resource-group'
  ADF_NAME: 'your-adf-name'
  UAMI_CLIENT_ID: ${{ secrets.AZURE_UAMI_CLIENT_ID }} # Client ID of your user-assigned managed identity

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC with Azure
      
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install ADF Utilities
      run: npm install -g @microsoft/azure-data-factory-utilities

    - name: Login to Azure with UAMI
      uses: azure/login@v1
      with:
        client-id: ${{ env.UAMI_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Generate ARM templates with linked templates
      run: |
        npm run build export -- \
          --subscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
          --resourceGroup ${{ env.RESOURCE_GROUP }} \
          --factoryName ${{ env.ADF_NAME }} \
          --outputFolder ./arm-templates \
          --linkedTemplatesTargetPath "https://${{ env.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/${{ env.CONTAINER_NAME }}/linkedTemplates" \
          --linkedTemplatesBaseUrl "https://${{ env.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/${{ env.CONTAINER_NAME }}" \
          --skipPublish

    - name: Upload templates to storage using UAMI
      run: |
        # No need for storage keys - using managed identity
        az storage blob upload-batch \
          --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
          --destination ${{ env.CONTAINER_NAME }} \
          --source ./arm-templates \
          --overwrite \
          --auth-mode login

  deploy:
    needs: generate-and-upload
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      
    steps:
    - name: Login to Azure with UAMI
      uses: azure/login@v1
      with:
        client-id: ${{ env.UAMI_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy ADF with linked templates
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: https://${{ env.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/${{ env.CONTAINER_NAME }}/ARMTemplateForFactory.json
        parameters: https://${{ env.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/${{ env.CONTAINER_NAME }}/ARMTemplateParametersForFactory.json
        deploymentMode: Incremental